modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.epicfight_annoyingvillagers]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.epicfight_annoyingvillagers]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.epicfight_annoyingvillagers]]
    modId="epicfight"
    mandatory=true
    versionRange="[20.13, )"
    ordering="AFTER"
    side="BOTH"
[[dependencies.epicfight_annoyingvillagers]]
    modId="wom"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.epicfight_annoyingvillagers]]
    modId="efn"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.epicfight_annoyingvillagers]]
    modId="epicfight_awaken"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.epicfight_annoyingvillagers]]
    modId="annoyingvillagers"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
